console.log("hello");
hello = "hello world";
console.log(hello);   
let a = 10;
let b = 20;
let c = a + b;
console.log(c);
let d = a * b;
console.log(d);
let e = a / b;
console.log(e);
let f = a - b;
console.log(f);
let g = a % b;
console.log(g);
let h = a ** b;
console.log(h);
let i = a++;
console.log(i);
let j = ++a;
console.log(j);
let k = a--;
console.log(k);
let l = --a;
console.log(l);
let m = a == b;
console.log(m);
let n = a != b;
console.log(n);
let o = a > b;
console.log(o);
let p = a < b;
console.log(p);
let q = a >= b;
console.log(q);
let r = a <= b;
console.log(r);
let s = a && b;
console.log(s);
let t = a || b;
console.log(t);
let u = !a;
console.log(u);
let v = a ?? b;
console.log(v);